#include "scanconverter.h"

#ifndef SRC_PARAMS_H_
#define SRC_PARAMS_H_

#define BEAMFORMER_BASE_ADDRESS 0x44A00000
#define BEAMFORMER_STATUS_REG   (BEAMFORMER_BASE_ADDRESS + 0x0)
#define BEAMFORMER_FIFO_REG     (BEAMFORMER_BASE_ADDRESS + 0x4)
#define BEAMFORMER_BRAM_REG     (BEAMFORMER_BASE_ADDRESS + 0x8)
#define BEAMFORMER_COMMAND_REG  (BEAMFORMER_BASE_ADDRESS + 0xC)
#define BEAMFORMER_OPTIONS_REG  (BEAMFORMER_BASE_ADDRESS + 0x10)
#define BEAMFORMER_RF_DEPTH_REG (BEAMFORMER_BASE_ADDRESS + 0x14)
#define BEAMFORMER_ZERO_OFF_REG (BEAMFORMER_BASE_ADDRESS + 0x18)
#define BEAMFORMER_STATUS2_REG  (BEAMFORMER_BASE_ADDRESS + 0x1C)
#define BEAMFORMER_STATUS3_REG  (BEAMFORMER_BASE_ADDRESS + 0x20)
#define BEAMFORMER_STATUS4_REG  (BEAMFORMER_BASE_ADDRESS + 0x24)
#define BEAMFORMER_STATUS5_REG  (BEAMFORMER_BASE_ADDRESS + 0x28)
#define BEAMFORMER_STATUS6_REG  (BEAMFORMER_BASE_ADDRESS + 0x2C)
#define BEAMFORMER_STATUS7_REG  (BEAMFORMER_BASE_ADDRESS + 0x30)
// Location in memory where the BF has to write outputs
#define NAPPE_MEMORY            (DDR_BASEADDR + 0x40000000)
// Location in memory where the SC has to write outputs
#define SC_IMAGE_MEMORY         (DDR_BASEADDR + 0x08000000)
// HDMI image resolution
// RESOLUTION_1920x1080, RESOLUTION_1600x900, RESOLUTION_1280x720,
// RESOLUTION_1024x768, RESOLUTION_800x600, RESOLUTION_640x480
#define RESOLUTION              RESOLUTION_1920x1080
// Set at 1 to use the SC block in master mode (faster).
#define USE_SC_MASTER           1
// SC image size at boot. Can be modified at runtime with the options string.
#define BOOT_IMG_WIDTH          356
#define BOOT_IMG_HEIGHT         300

#endif /* SRC_PARAMS_H_ */
