#ifndef __PLATFORM_CONFIG_H_
#define __PLATFORM_CONFIG_H_


#define PLATFORM_EMAC_BASEADDR XPAR_AXI_ETHERNET_0_BASEADDR

#define PLATFORM_TIMER_BASEADDR XPAR_AXI_TIMER_BASEADDR
#define PLATFORM_TIMER_INTERRUPT_INTR XPAR_AXI_INTC_AXI_TIMER_INTERRUPT_INTR
#define PLATFORM_TIMER_INTERRUPT_MASK (1 << XPAR_AXI_INTC_AXI_TIMER_INTERRUPT_INTR)


#endif
